#pragma once
#include "TwoD/Serialization/Serialization.hpp"

//#include <SDL3/SDL_events.h>

TD_ENUM(
	(TD_NAMESPACE(TwoD), TD_NAME(EventType)),
	(
		TD_ENUM_FIELD(INVALID),
		TD_ENUM_FIELD(QUIT),

		TD_ENUM_FIELD(WINDOW_RESIZED),
		TD_ENUM_FIELD(WINDOW_CLOSE_REQUESTED),

		TD_ENUM_FIELD(KEY_DOWN),
		TD_ENUM_FIELD(KEY_UP),
		TD_ENUM_FIELD(TEXT_EDITING),
		TD_ENUM_FIELD(TEXT_INPUT),

		TD_ENUM_FIELD(MOUSE_MOTION),
		TD_ENUM_FIELD(MOUSE_BUTTON_DOWN),
		TD_ENUM_FIELD(MOUSE_BUTTON_UP),
		TD_ENUM_FIELD(MOUSE_WHEEL),

		TD_ENUM_FIELD(CLIPBOARD_UPDATE)
	)
)