#pragma once
#include "TwoD/Core/YAML.hpp"

//#include <SDL3/SDL_events.h>

TD_YAML_ENUM(TwoD, EventType,
	TD_YAML_ENUM_FIELD(INVALID),
	TD_YAML_ENUM_FIELD(QUIT),

	TD_YAML_ENUM_FIELD(WINDOW_RESIZED),
	TD_YAML_ENUM_FIELD(WINDOW_CLOSE_REQUESTED),

	TD_YAML_ENUM_FIELD(KEY_DOWN),
	TD_YAML_ENUM_FIELD(KEY_UP),
	TD_YAML_ENUM_FIELD(TEXT_EDITING),
	TD_YAML_ENUM_FIELD(TEXT_INPUT),

	TD_YAML_ENUM_FIELD(MOUSE_MOTION),
	TD_YAML_ENUM_FIELD(MOUSE_BUTTON_DOWN),
	TD_YAML_ENUM_FIELD(MOUSE_BUTTON_UP),
	TD_YAML_ENUM_FIELD(MOUSE_WHEEL),

	TD_YAML_ENUM_FIELD(CLIPBOARD_UPDATE)
)