#pragma once
#include "TwoD/Core/YAML.hpp"

namespace TwoD
{
    class Window;
}

TD_YAML_ENUM_WITH_BASE(TwoD, WindowFlags, uint64_t,
	TD_YAML_ENUM_FIELD(FULLSCREEN, 0x0000000000000001ULL),
	TD_YAML_ENUM_FIELD(OPENGL, 0x0000000000000002ULL),
	TD_YAML_ENUM_FIELD(OCCLUDED, 0x0000000000000004ULL),
	TD_YAML_ENUM_FIELD(HIDDEN, 0x0000000000000008ULL),
	TD_YAML_ENUM_FIELD(BORDERLESS, 0x0000000000000010ULL),
	TD_YAML_ENUM_FIELD(RESIZABLE, 0x0000000000000020ULL),
	TD_YAML_ENUM_FIELD(MINIMIZED, 0x0000000000000040ULL),
	TD_YAML_ENUM_FIELD(MAXIMIZED, 0x0000000000000080ULL),
	TD_YAML_ENUM_FIELD(MOUSE_GRABBED, 0x0000000000000100ULL),
	TD_YAML_ENUM_FIELD(INPUT_FOCUS, 0x0000000000000200ULL),
	TD_YAML_ENUM_FIELD(MOUSE_FOCUS, 0x0000000000000400ULL),
	TD_YAML_ENUM_FIELD(EXTERNAL, 0x0000000000000800ULL),
	TD_YAML_ENUM_FIELD(MODAL, 0x0000000000001000ULL),
	TD_YAML_ENUM_FIELD(HIGH_PIXEL_DENSITY, 0x0000000000002000ULL),
	TD_YAML_ENUM_FIELD(MOUSE_CAPTURE, 0x0000000000004000ULL),
	TD_YAML_ENUM_FIELD(MOUSE_RELATIVE_MODE, 0x0000000000008000ULL),
	TD_YAML_ENUM_FIELD(ALWAYS_ON_TOP, 0x0000000000010000ULL),
	TD_YAML_ENUM_FIELD(UTILITY, 0x0000000000020000ULL),
	TD_YAML_ENUM_FIELD(TOOLTIP, 0x0000000000040000ULL),
	TD_YAML_ENUM_FIELD(POPUP_MENU, 0x0000000000080000ULL),
	TD_YAML_ENUM_FIELD(KEYBOARD_GRABBED, 0x0000000000100000ULL),
	TD_YAML_ENUM_FIELD(VULKAN, 0x0000000010000000ULL),
	TD_YAML_ENUM_FIELD(METAL, 0x0000000020000000ULL),
	TD_YAML_ENUM_FIELD(W_TRANSPARENT, 0x0000000040000000ULL),
	TD_YAML_ENUM_FIELD(NOT_FOCUSABLE, 0x0000000080000000ULL)
)

TD_YAML_STRUCT(TwoD, WindowInfo,
	TD_YAML_STRUCT_FIELD(int, width),
	TD_YAML_STRUCT_FIELD(int, height),
	TD_YAML_STRUCT_FIELD(std::string_view, title),
	TD_YAML_STRUCT_FIELD(TwoD::WindowFlags, windowFlags)
)

namespace TwoD::SDL
{
    // *****************************************************
    // Declerations ****************************************
    // *****************************************************

    class Surface;
    class Texture;
    class Sampler;
    class Buffer;
    class CommandBuffer;
    class CopyPass;
    class GraphicsPipeline;
    class RenderPass;
    class Shader;
    class TransferBuffer;
}
	
// *****************************************************
// Misc ************************************************
// *****************************************************

TD_YAML_ENUM(TwoD::SDL, Filter,
    TD_YAML_ENUM_FIELD(NEAREST),
    TD_YAML_ENUM_FIELD(LINEAR)
)
TD_YAML_ENUM(TwoD::SDL, CompareOp,
    TD_YAML_ENUM_FIELD(INVALID),
    TD_YAML_ENUM_FIELD(NEVER),
    TD_YAML_ENUM_FIELD(LESS),
    TD_YAML_ENUM_FIELD(EQUAL),
    TD_YAML_ENUM_FIELD(LESS_OR_EQUAL),
    TD_YAML_ENUM_FIELD(GREATER),
    TD_YAML_ENUM_FIELD(NOT_EQUAL),
    TD_YAML_ENUM_FIELD(GREATER_OR_EQUAL),
    TD_YAML_ENUM_FIELD(ALWAYS)
)
TD_YAML_ENUM(TwoD::SDL, BlendFactor,
    TD_YAML_ENUM_FIELD(INVALID),
    TD_YAML_ENUM_FIELD(ZERO),
    TD_YAML_ENUM_FIELD(ONE),
    TD_YAML_ENUM_FIELD(SRC_COLOR),
    TD_YAML_ENUM_FIELD(ONE_MINUS_SRC_COLOR),
    TD_YAML_ENUM_FIELD(DST_COLOR),
    TD_YAML_ENUM_FIELD(ONE_MINUS_DST_COLOR),
    TD_YAML_ENUM_FIELD(SRC_ALPHA),
    TD_YAML_ENUM_FIELD(ONE_MINUS_SRC_ALPHA),
    TD_YAML_ENUM_FIELD(DST_ALPHA),
    TD_YAML_ENUM_FIELD(ONE_MINUS_DST_ALPHA),
    TD_YAML_ENUM_FIELD(CONSTANT_COLOR),
    TD_YAML_ENUM_FIELD(ONE_MINUS_CONSTANT_COLOR),
    TD_YAML_ENUM_FIELD(SRC_ALPHA_SATURATE)
)
TD_YAML_ENUM(TwoD::SDL, BlendOp,
    TD_YAML_ENUM_FIELD(INVALID),
    TD_YAML_ENUM_FIELD(ADD),
    TD_YAML_ENUM_FIELD(SUBTRACT),
    TD_YAML_ENUM_FIELD(REVERSE_SUBTRACT),
    TD_YAML_ENUM_FIELD(MIN),
    TD_YAML_ENUM_FIELD(MAX)
)
TD_YAML_ENUM(TwoD::SDL, SampleCount,
    TD_YAML_ENUM_FIELD(ONE),
    TD_YAML_ENUM_FIELD(TWO),
    TD_YAML_ENUM_FIELD(FOUR),
    TD_YAML_ENUM_FIELD(EIGHT)
)
TD_YAML_STRUCT(TwoD::SDL, Rect,
    TD_YAML_STRUCT_FIELD(uint32_t, x, 0),
    TD_YAML_STRUCT_FIELD(uint32_t, y, 0),
    TD_YAML_STRUCT_FIELD(uint32_t, w, 0),
    TD_YAML_STRUCT_FIELD(uint32_t, h, 0)
)

// *****************************************************
// Buffer **********************************************
// *****************************************************

TD_YAML_ENUM_WITH_BASE(TwoD::SDL, BufferUsage, uint32_t,
	TD_YAML_ENUM_FIELD(VERTEX, (1u << 0)),
	TD_YAML_ENUM_FIELD(INDEX, (1u << 1)),
	TD_YAML_ENUM_FIELD(INDIRECT, (1u << 2)),
	TD_YAML_ENUM_FIELD(GRAPHICS_STORAGE_READ, (1u << 3)),
	TD_YAML_ENUM_FIELD(COMPUTE_STORAGE_READ, (1u << 4)),
	TD_YAML_ENUM_FIELD(COMPUTE_STORAGE_WRITE, (1u << 5))
)
TD_YAML_STRUCT(TwoD::SDL, BufferInfo,
	TD_YAML_STRUCT_FIELD(TwoD::SDL::BufferUsage, usage),
	TD_YAML_STRUCT_FIELD(uint32_t, size)
)

// *****************************************************
// TransferBuffer **************************************
// *****************************************************

TD_YAML_ENUM(TwoD::SDL, TransferBufferUsage,
	TD_YAML_ENUM_FIELD(UPLOAD),
	TD_YAML_ENUM_FIELD(DOWNLOAD)
)
TD_YAML_STRUCT(TwoD::SDL, TransferBufferInfo,
	TD_YAML_STRUCT_FIELD(TwoD::SDL::TransferBufferUsage, usage),
	TD_YAML_STRUCT_FIELD(uint32_t, size)
)

// *****************************************************
// Texture *********************************************
// *****************************************************

TD_YAML_ENUM(TwoD::SDL, TextureFormat,
    TD_YAML_ENUM_FIELD(INVALID),
    TD_YAML_ENUM_FIELD(A8_UNORM),
    TD_YAML_ENUM_FIELD(R8_UNORM),
    TD_YAML_ENUM_FIELD(R8G8_UNORM),
    TD_YAML_ENUM_FIELD(R8G8B8A8_UNORM),
    TD_YAML_ENUM_FIELD(R16_UNORM),
    TD_YAML_ENUM_FIELD(R16G16_UNORM),
    TD_YAML_ENUM_FIELD(R16G16B16A16_UNORM),
    TD_YAML_ENUM_FIELD(R10G10B10A2_UNORM),
    TD_YAML_ENUM_FIELD(B5G6R5_UNORM),
    TD_YAML_ENUM_FIELD(B5G5R5A1_UNORM),
    TD_YAML_ENUM_FIELD(B4G4R4A4_UNORM),
    TD_YAML_ENUM_FIELD(B8G8R8A8_UNORM),
    TD_YAML_ENUM_FIELD(BC1_RGBA_UNORM),
    TD_YAML_ENUM_FIELD(BC2_RGBA_UNORM),
    TD_YAML_ENUM_FIELD(BC3_RGBA_UNORM),
    TD_YAML_ENUM_FIELD(BC4_R_UNORM),
    TD_YAML_ENUM_FIELD(BC5_RG_UNORM),
    TD_YAML_ENUM_FIELD(BC7_RGBA_UNORM),
    TD_YAML_ENUM_FIELD(BC6H_RGB_FLOAT),
    TD_YAML_ENUM_FIELD(BC6H_RGB_UFLOAT),
    TD_YAML_ENUM_FIELD(R8_SNORM),
    TD_YAML_ENUM_FIELD(R8G8_SNORM),
    TD_YAML_ENUM_FIELD(R8G8B8A8_SNORM),
    TD_YAML_ENUM_FIELD(R16_SNORM),
    TD_YAML_ENUM_FIELD(R16G16_SNORM),
    TD_YAML_ENUM_FIELD(R16G16B16A16_SNORM),
    TD_YAML_ENUM_FIELD(R16_FLOAT),
    TD_YAML_ENUM_FIELD(R16G16_FLOAT),
    TD_YAML_ENUM_FIELD(R16G16B16A16_FLOAT),
    TD_YAML_ENUM_FIELD(R32_FLOAT),
    TD_YAML_ENUM_FIELD(R32G32_FLOAT),
    TD_YAML_ENUM_FIELD(R32G32B32A32_FLOAT),
    TD_YAML_ENUM_FIELD(R11G11B10_UFLOAT),
    TD_YAML_ENUM_FIELD(R8_UINT),
    TD_YAML_ENUM_FIELD(R8G8_UINT),
    TD_YAML_ENUM_FIELD(R8G8B8A8_UINT),
    TD_YAML_ENUM_FIELD(R16_UINT),
    TD_YAML_ENUM_FIELD(R16G16_UINT),
    TD_YAML_ENUM_FIELD(R16G16B16A16_UINT),
    TD_YAML_ENUM_FIELD(R32_UINT),
    TD_YAML_ENUM_FIELD(R32G32_UINT),
    TD_YAML_ENUM_FIELD(R32G32B32A32_UINT),
    TD_YAML_ENUM_FIELD(R8_INT),
    TD_YAML_ENUM_FIELD(R8G8_INT),
    TD_YAML_ENUM_FIELD(R8G8B8A8_INT),
    TD_YAML_ENUM_FIELD(R16_INT),
    TD_YAML_ENUM_FIELD(R16G16_INT),
    TD_YAML_ENUM_FIELD(R16G16B16A16_INT),
    TD_YAML_ENUM_FIELD(R32_INT),
    TD_YAML_ENUM_FIELD(R32G32_INT),
    TD_YAML_ENUM_FIELD(R32G32B32A32_INT),
    TD_YAML_ENUM_FIELD(R8G8B8A8_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(B8G8R8A8_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(BC1_RGBA_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(BC2_RGBA_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(BC3_RGBA_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(BC7_RGBA_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(D16_UNORM),
    TD_YAML_ENUM_FIELD(D24_UNORM),
    TD_YAML_ENUM_FIELD(D32_FLOAT),
    TD_YAML_ENUM_FIELD(D24_UNORM_S8_UINT),
    TD_YAML_ENUM_FIELD(D32_FLOAT_S8_UINT),
    TD_YAML_ENUM_FIELD(ASTC_4x4_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_5x4_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_5x5_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_6x5_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_6x6_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_8x5_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_8x6_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_8x8_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_10x5_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_10x6_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_10x8_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_10x10_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_12x10_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_12x12_UNORM),
    TD_YAML_ENUM_FIELD(ASTC_4x4_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_5x4_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_5x5_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_6x5_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_6x6_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_8x5_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_8x6_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_8x8_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_10x5_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_10x6_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_10x8_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_10x10_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_12x10_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_12x12_UNORM_SRGB),
    TD_YAML_ENUM_FIELD(ASTC_4x4_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_5x4_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_5x5_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_6x5_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_6x6_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_8x5_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_8x6_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_8x8_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_10x5_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_10x6_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_10x8_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_10x10_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_12x10_FLOAT),
    TD_YAML_ENUM_FIELD(ASTC_12x12_FLOAT)
)
TD_YAML_ENUM(TwoD::SDL, TextureType,
    TD_YAML_ENUM_FIELD(TWO_D),
    TD_YAML_ENUM_FIELD(TWO_D_ARRAY),
    TD_YAML_ENUM_FIELD(THREE_D),
    TD_YAML_ENUM_FIELD(CUBE),
    TD_YAML_ENUM_FIELD(CUBE_ARRAY)
)
TD_YAML_ENUM_WITH_BASE(TwoD::SDL, TextureUsageFlags, uint32_t,
    TD_YAML_ENUM_FIELD(SAMPLER, (1u << 0)),
    TD_YAML_ENUM_FIELD(COLOR_TARGET, (1u << 1)),
    TD_YAML_ENUM_FIELD(DEPTH_STENCIL_TARGET, (1u << 2)),
    TD_YAML_ENUM_FIELD(GRAPHICS_STORAGE_READ, (1u << 3)),
    TD_YAML_ENUM_FIELD(COMPUTE_STORAGE_READ, (1u << 4)),
    TD_YAML_ENUM_FIELD(COMPUTE_STORAGE_WRITE, (1u << 5)),
    TD_YAML_ENUM_FIELD(COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE, (1u << 6))
)
TD_YAML_STRUCT(TwoD::SDL, TextureInfo,
    TD_YAML_STRUCT_FIELD(TwoD::SDL::TextureType, type),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::TextureFormat, format),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::TextureUsageFlags, usage),
    TD_YAML_STRUCT_FIELD(uint32_t, width),
    TD_YAML_STRUCT_FIELD(uint32_t, height),
    TD_YAML_STRUCT_FIELD(uint32_t, layerCountOrDepth, 1),
    TD_YAML_STRUCT_FIELD(uint32_t, numLevels, 1),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::SampleCount, sampleCount, TwoD::SDL::SampleCount::ONE)
)

// *****************************************************
// Sampler *********************************************
// *****************************************************

TD_YAML_ENUM(TwoD::SDL, SamplerMipmapMode,
    TD_YAML_ENUM_FIELD(NEAREST),
    TD_YAML_ENUM_FIELD(LINEAR)
)
TD_YAML_ENUM(TwoD::SDL, SamplerAddressMode,
    TD_YAML_ENUM_FIELD(REPEAT),
    TD_YAML_ENUM_FIELD(MIRRORED_REPEAT),
    TD_YAML_ENUM_FIELD(CLAMP_TO_EDGE)
)
TD_YAML_STRUCT(TwoD::SDL, SamplerInfo,
    TD_YAML_STRUCT_FIELD(TwoD::SDL::Filter, minFilter),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::Filter, magFilter),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::SamplerMipmapMode, mipmapMode),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::SamplerAddressMode, addressModeU),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::SamplerAddressMode, addressModeV),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::SamplerAddressMode, addressModeW),
    TD_YAML_STRUCT_FIELD(float, mipLodBias),
    TD_YAML_STRUCT_FIELD(float, maxAnisotropy),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::CompareOp, compareOp),
    TD_YAML_STRUCT_FIELD(float, minLod),
    TD_YAML_STRUCT_FIELD(float, maxLod),
    TD_YAML_STRUCT_FIELD(bool, enableAnisotropy),
    TD_YAML_STRUCT_FIELD(bool, enableCompare)
)

// *****************************************************
// Shader **********************************************
// *****************************************************

TD_YAML_ENUM_WITH_BASE(TwoD::SDL, ShaderFormat, uint32_t,
    TD_YAML_ENUM_FIELD(INVALID,  0),
    TD_YAML_ENUM_FIELD(PRIVATE,  (1u << 0)),
    TD_YAML_ENUM_FIELD(SPIRV,    (1u << 1)),
    TD_YAML_ENUM_FIELD(DXBC,     (1u << 2)),
    TD_YAML_ENUM_FIELD(DXIL,     (1u << 3)),
    TD_YAML_ENUM_FIELD(MSL,      (1u << 4)),
    TD_YAML_ENUM_FIELD(METALLIB, (1u << 5))
)
TD_YAML_ENUM(TwoD::SDL, ShaderStage,
    TD_YAML_ENUM_FIELD(VERTEX),
    TD_YAML_ENUM_FIELD(FRAGMENT)
)
TD_YAML_STRUCT(TwoD::SDL, ShaderInfo,
    TD_YAML_STRUCT_FIELD(uint32_t, codeSize),
    TD_YAML_STRUCT_FIELD_NO_PARSING(uint8_t*, code),
    TD_YAML_STRUCT_FIELD(std::string, entrypoint),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::ShaderFormat, format),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::ShaderStage, stage),
    TD_YAML_STRUCT_FIELD(uint32_t, numSamplers),
    TD_YAML_STRUCT_FIELD(uint32_t, numStorageTextures),
    TD_YAML_STRUCT_FIELD(uint32_t, numStorageBuffers),
    TD_YAML_STRUCT_FIELD(uint32_t, numUniformBuffers)
)

// *****************************************************
// RenderPass ******************************************
// *****************************************************

TD_YAML_ENUM(TwoD::SDL, IndexElementSize,
    TD_YAML_ENUM_FIELD(SIXTEEN_BIT),
    TD_YAML_ENUM_FIELD(THIRTY_TWO_BIT)
)
TD_YAML_STRUCT(TwoD::SDL, TextureSamplerBinding,
    TD_YAML_STRUCT_FIELD_NO_PARSING(TwoD::SDL::Texture*, texture),
    TD_YAML_STRUCT_FIELD_NO_PARSING(TwoD::SDL::Sampler*, sampler)
)
TD_YAML_STRUCT(TwoD::SDL, BufferBinding,
    TD_YAML_STRUCT_FIELD_NO_PARSING(TwoD::SDL::Buffer*, buffer),
    TD_YAML_STRUCT_FIELD(uint32_t, offset)
)

// *****************************************************
// CopyPass ********************************************
// *****************************************************

TD_YAML_STRUCT(TwoD::SDL, TextureTransferInfo,
    TD_YAML_STRUCT_FIELD_NO_PARSING(TwoD::SDL::TransferBuffer*, transferBuffer),
    TD_YAML_STRUCT_FIELD(uint32_t, offset),
    TD_YAML_STRUCT_FIELD(uint32_t, pixelsPerRow),
    TD_YAML_STRUCT_FIELD(uint32_t, rowsPerLayer)
)
TD_YAML_STRUCT(TwoD::SDL, TextureRegion,
    TD_YAML_STRUCT_FIELD_NO_PARSING(TwoD::SDL::Texture*, texture),
    TD_YAML_STRUCT_FIELD(uint32_t, mipLevel),
    TD_YAML_STRUCT_FIELD(uint32_t, layer),
    TD_YAML_STRUCT_FIELD(uint32_t, x),
    TD_YAML_STRUCT_FIELD(uint32_t, y),
    TD_YAML_STRUCT_FIELD(uint32_t, z),
    TD_YAML_STRUCT_FIELD(uint32_t, w),
    TD_YAML_STRUCT_FIELD(uint32_t, h),
    TD_YAML_STRUCT_FIELD(uint32_t, d)
)
TD_YAML_STRUCT(TwoD::SDL, TransferBufferLocation,
    TD_YAML_STRUCT_FIELD_NO_PARSING(const TwoD::SDL::TransferBuffer*, transferBuffer),
    TD_YAML_STRUCT_FIELD(uint32_t, offset)
)
TD_YAML_STRUCT(TwoD::SDL, BufferRegion,
    TD_YAML_STRUCT_FIELD_NO_PARSING(const TwoD::SDL::Buffer*, buffer),
    TD_YAML_STRUCT_FIELD(uint32_t, offset),
    TD_YAML_STRUCT_FIELD(uint32_t, size)
)

// *****************************************************
// GraphicsPipeline ************************************
// *****************************************************

TD_YAML_ENUM(TwoD::SDL, VertexElementFormat,
    TD_YAML_ENUM_FIELD(INVALID),
    TD_YAML_ENUM_FIELD(INT),
    TD_YAML_ENUM_FIELD(INT2),
    TD_YAML_ENUM_FIELD(INT3),
    TD_YAML_ENUM_FIELD(INT4),
    TD_YAML_ENUM_FIELD(UINT),
    TD_YAML_ENUM_FIELD(UINT2),
    TD_YAML_ENUM_FIELD(UINT3),
    TD_YAML_ENUM_FIELD(UINT4),
    TD_YAML_ENUM_FIELD(FLOAT),
    TD_YAML_ENUM_FIELD(FLOAT2),
    TD_YAML_ENUM_FIELD(FLOAT3),
    TD_YAML_ENUM_FIELD(FLOAT4),
    TD_YAML_ENUM_FIELD(BYTE2),
    TD_YAML_ENUM_FIELD(BYTE4),
    TD_YAML_ENUM_FIELD(UBYTE2),
    TD_YAML_ENUM_FIELD(UBYTE4),
    TD_YAML_ENUM_FIELD(BYTE2_NORM),
    TD_YAML_ENUM_FIELD(BYTE4_NORM)
)
TD_YAML_ENUM(TwoD::SDL, VertexInputRate,
    TD_YAML_ENUM_FIELD(VERTEX),
    TD_YAML_ENUM_FIELD(INSTANCE)
)
TD_YAML_ENUM(TwoD::SDL, PrimitiveType,
    TD_YAML_ENUM_FIELD(TRIANGLELIST),
    TD_YAML_ENUM_FIELD(TRIANGLESTRIP),
    TD_YAML_ENUM_FIELD(LINELIST),
    TD_YAML_ENUM_FIELD(LINESTRIP),
    TD_YAML_ENUM_FIELD(POINTLIST)
)
TD_YAML_ENUM(TwoD::SDL, FrontFace,
    (COUNTER_CLOCKWISE),
    (CLOCKWISE)
)
TD_YAML_ENUM(TwoD::SDL, CullMode,
    TD_YAML_ENUM_FIELD(NONE),
    TD_YAML_ENUM_FIELD(FRONT),
    TD_YAML_ENUM_FIELD(BACK)
)
TD_YAML_ENUM(TwoD::SDL, FillMode,
    TD_YAML_ENUM_FIELD(FILL),
    TD_YAML_ENUM_FIELD(LINE)
)
TD_YAML_ENUM(TwoD::SDL, StencilOp,
    TD_YAML_ENUM_FIELD(INVALID),
    TD_YAML_ENUM_FIELD(KEEP),
    TD_YAML_ENUM_FIELD(ZERO),
    TD_YAML_ENUM_FIELD(REPLACE),
    TD_YAML_ENUM_FIELD(INCREMENT_AND_CLAMP),
    TD_YAML_ENUM_FIELD(DECREMENT_AND_CLAMP),
    TD_YAML_ENUM_FIELD(INVERT),
    TD_YAML_ENUM_FIELD(INCREMENT_AND_WRAP),
    TD_YAML_ENUM_FIELD(DECREMENT_AND_WRAP)
)
TD_YAML_ENUM_WITH_BASE(TwoD::SDL, ColorComponentFlags, uint8_t,
    TD_YAML_ENUM_FIELD(R, (1u << 0)),
    TD_YAML_ENUM_FIELD(G, (1u << 1)),
    TD_YAML_ENUM_FIELD(B, (1u << 2)),
    TD_YAML_ENUM_FIELD(A, (1u << 3))
)
TD_YAML_STRUCT(TwoD::SDL, ColorTargetBlendState,
	TD_YAML_STRUCT_FIELD(TwoD::SDL::BlendFactor, srcColorBlendfactor, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::BlendFactor, dstColorBlendfactor, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::BlendOp, colorBlendOp, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::BlendFactor, srcAlphaBlendfactor, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::BlendFactor, dstAlphaBlendfactor, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::BlendOp, alphaBlendOp, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::ColorComponentFlags, colorWriteMask, {}),
    TD_YAML_STRUCT_FIELD(bool, enableBlend, false),
    TD_YAML_STRUCT_FIELD(bool, enableColorWriteMask, false)
)
TD_YAML_STRUCT(TwoD::SDL, VertexBufferDescription,
    TD_YAML_STRUCT_FIELD(uint32_t, slot),
    TD_YAML_STRUCT_FIELD(uint32_t, pitch),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::VertexInputRate, inputRate)
)
TD_YAML_STRUCT(TwoD::SDL, VertexAttribute,
    TD_YAML_STRUCT_FIELD(uint32_t, location),
    TD_YAML_STRUCT_FIELD(uint32_t, bufferSlot),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::VertexElementFormat, format),
    TD_YAML_STRUCT_FIELD(uint32_t, offset)
)
TD_YAML_STRUCT(TwoD::SDL, StencilOpState,
    TD_YAML_STRUCT_FIELD(TwoD::SDL::StencilOp, failOp, TwoD::SDL::StencilOp::INVALID),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::StencilOp, passOp, TwoD::SDL::StencilOp::INVALID),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::StencilOp, depthFailOp, TwoD::SDL::StencilOp::INVALID),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::CompareOp, compareOp, TwoD::SDL::CompareOp::INVALID)
)
TD_YAML_STRUCT(TwoD::SDL, ColorTargetDescription,
    TD_YAML_STRUCT_FIELD(TwoD::SDL::TextureFormat, format, TwoD::SDL::TextureFormat::INVALID),
	TD_YAML_STRUCT_FIELD(TwoD::SDL::ColorTargetBlendState, blendState)
)
TD_YAML_STRUCT(TwoD::SDL, VertexInputState,
	TD_YAML_STRUCT_FIELD(std::vector<TwoD::SDL::VertexBufferDescription>, vertexBufferDescriptions, {}),
	TD_YAML_STRUCT_FIELD(std::vector<TwoD::SDL::VertexAttribute>, vertexAttributes, {})
)
TD_YAML_STRUCT(TwoD::SDL, RasterizerState,
    TD_YAML_STRUCT_FIELD(TwoD::SDL::FillMode, fillMode, TwoD::SDL::FillMode::FILL),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::CullMode, cullMode, TwoD::SDL::CullMode::NONE),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::FrontFace, frontFace, TwoD::SDL::FrontFace::COUNTER_CLOCKWISE),
    TD_YAML_STRUCT_FIELD(float, depthBiasConstantFactor, 0.0f),
    TD_YAML_STRUCT_FIELD(float, depthBiasClamp, 0.0f),
    TD_YAML_STRUCT_FIELD(float, depthBiasSlopeFactor, 0.0f),
    TD_YAML_STRUCT_FIELD(bool, enableDepthBias, false),
    TD_YAML_STRUCT_FIELD(bool, enableDepthClip, false)
)
TD_YAML_STRUCT(TwoD::SDL, MultisampleState,
    TD_YAML_STRUCT_FIELD(TwoD::SDL::SampleCount, sampleCount, TwoD::SDL::SampleCount::ONE),
    TD_YAML_STRUCT_FIELD(uint32_t, sampleMask, 0),
    TD_YAML_STRUCT_FIELD(bool, enableMask, false)
)
TD_YAML_STRUCT(TwoD::SDL, DepthStencilState,
    TD_YAML_STRUCT_FIELD(TwoD::SDL::CompareOp, compareOp, TwoD::SDL::CompareOp::INVALID),
	TD_YAML_STRUCT_FIELD(TwoD::SDL::StencilOpState, backStencilState, {}),
	TD_YAML_STRUCT_FIELD(TwoD::SDL::StencilOpState, frontStencilState, {}),
    TD_YAML_STRUCT_FIELD(uint8_t, compareMask, 0),
    TD_YAML_STRUCT_FIELD(uint8_t, writeMask, 0),
    TD_YAML_STRUCT_FIELD(bool, enableDepthTest, false),
    TD_YAML_STRUCT_FIELD(bool, enableDepthWrite, false),
    TD_YAML_STRUCT_FIELD(bool, enableStencilTest, false)
)
TD_YAML_STRUCT(TwoD::SDL, GraphicsPipelineTargetInfo,
    TD_YAML_STRUCT_FIELD(std::vector<TwoD::SDL::ColorTargetDescription>, colorTargetDescriptions),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::TextureFormat, depthStencilFormat, TwoD::SDL::TextureFormat::INVALID),
    TD_YAML_STRUCT_FIELD(bool, hasDepthStencilTarget, false)
)
TD_YAML_STRUCT(TwoD::SDL, GraphicsPipelineInfo,
    TD_YAML_STRUCT_FIELD_NO_PARSING(TwoD::SDL::Shader*, vertexShader, nullptr),
    TD_YAML_STRUCT_FIELD_NO_PARSING(TwoD::SDL::Shader*, fragmentShader, nullptr),
	TD_YAML_STRUCT_FIELD(TwoD::SDL::VertexInputState, vertexInputState, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::PrimitiveType, primitiveType, TwoD::SDL::PrimitiveType::TRIANGLELIST),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::RasterizerState, rasterizerState, {}),
	TD_YAML_STRUCT_FIELD(TwoD::SDL::MultisampleState, multisampleState, {}),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::DepthStencilState, depthStencilState),
    TD_YAML_STRUCT_FIELD(TwoD::SDL::GraphicsPipelineTargetInfo, targetInfo)
)

// *****************************************************
// Surface *********************************************
// *****************************************************

TD_YAML_ENUM(TwoD::SDL, PixelFormat,
    TD_YAML_ENUM_FIELD(UNKNOWN, 0),
    TD_YAML_ENUM_FIELD(INDEX1LSB, 0x11100100u),
    TD_YAML_ENUM_FIELD(INDEX1MSB, 0x11200100u),
    TD_YAML_ENUM_FIELD(INDEX2LSB, 0x1c100200u),
    TD_YAML_ENUM_FIELD(INDEX2MSB, 0x1c200200u),
    TD_YAML_ENUM_FIELD(INDEX4LSB, 0x12100400u),
    TD_YAML_ENUM_FIELD(INDEX4MSB, 0x12200400u),
    TD_YAML_ENUM_FIELD(INDEX8, 0x13000801u),
    TD_YAML_ENUM_FIELD(RGB332, 0x14110801u),
    TD_YAML_ENUM_FIELD(XRGB4444, 0x15120c02u),
    TD_YAML_ENUM_FIELD(XBGR4444, 0x15520c02u),
    TD_YAML_ENUM_FIELD(XRGB1555, 0x15130f02u),
    TD_YAML_ENUM_FIELD(XBGR1555, 0x15530f02u),
    TD_YAML_ENUM_FIELD(ARGB4444, 0x15321002u),
    TD_YAML_ENUM_FIELD(RGBA4444, 0x15421002u),
    TD_YAML_ENUM_FIELD(ABGR4444, 0x15721002u),
    TD_YAML_ENUM_FIELD(BGRA4444, 0x15821002u),
    TD_YAML_ENUM_FIELD(ARGB1555, 0x15331002u),
    TD_YAML_ENUM_FIELD(RGBA5551, 0x15441002u),
    TD_YAML_ENUM_FIELD(ABGR1555, 0x15731002u),
    TD_YAML_ENUM_FIELD(BGRA5551, 0x15841002u),
    TD_YAML_ENUM_FIELD(RGB565, 0x15151002u),
    TD_YAML_ENUM_FIELD(BGR565, 0x15551002u),
    TD_YAML_ENUM_FIELD(RGB24, 0x17101803u),
    TD_YAML_ENUM_FIELD(BGR24, 0x17401803u),
    TD_YAML_ENUM_FIELD(XRGB8888, 0x16161804u),
    TD_YAML_ENUM_FIELD(RGBX8888, 0x16261804u),
    TD_YAML_ENUM_FIELD(XBGR8888, 0x16561804u),
    TD_YAML_ENUM_FIELD(BGRX8888, 0x16661804u),
    TD_YAML_ENUM_FIELD(ARGB8888, 0x16362004u),
    TD_YAML_ENUM_FIELD(RGBA8888, 0x16462004u),
    TD_YAML_ENUM_FIELD(ABGR8888, 0x16762004u),
    TD_YAML_ENUM_FIELD(BGRA8888, 0x16862004u),
    TD_YAML_ENUM_FIELD(XRGB2101010, 0x16172004u),
    TD_YAML_ENUM_FIELD(XBGR2101010, 0x16572004u),
    TD_YAML_ENUM_FIELD(ARGB2101010, 0x16372004u),
    TD_YAML_ENUM_FIELD(ABGR2101010, 0x16772004u),
    TD_YAML_ENUM_FIELD(RGB48, 0x18103006u),
    TD_YAML_ENUM_FIELD(BGR48, 0x18403006u),
    TD_YAML_ENUM_FIELD(RGBA64, 0x18204008u),
    TD_YAML_ENUM_FIELD(ARGB64, 0x18304008u),
    TD_YAML_ENUM_FIELD(BGRA64, 0x18504008u),
    TD_YAML_ENUM_FIELD(ABGR64, 0x18604008u),
    TD_YAML_ENUM_FIELD(RGB48_FLOAT, 0x1a103006u),
    TD_YAML_ENUM_FIELD(BGR48_FLOAT, 0x1a403006u),
    TD_YAML_ENUM_FIELD(RGBA64_FLOAT, 0x1a204008u),
    TD_YAML_ENUM_FIELD(ARGB64_FLOAT, 0x1a304008u),
    TD_YAML_ENUM_FIELD(BGRA64_FLOAT, 0x1a504008u),
    TD_YAML_ENUM_FIELD(ABGR64_FLOAT, 0x1a604008u),
    TD_YAML_ENUM_FIELD(RGB96_FLOAT, 0x1b10600cu),
    TD_YAML_ENUM_FIELD(BGR96_FLOAT, 0x1b40600cu),
    TD_YAML_ENUM_FIELD(RGBA128_FLOAT, 0x1b208010u),
    TD_YAML_ENUM_FIELD(ARGB128_FLOAT, 0x1b308010u),
    TD_YAML_ENUM_FIELD(BGRA128_FLOAT, 0x1b508010u),
    TD_YAML_ENUM_FIELD(ABGR128_FLOAT, 0x1b608010u),
    TD_YAML_ENUM_FIELD(YV12, 0x32315659),
    TD_YAML_ENUM_FIELD(IYUV, 0x56555949),
    TD_YAML_ENUM_FIELD(YUY2, 0x32595559),
    TD_YAML_ENUM_FIELD(UYVY, 0x59565955),
    TD_YAML_ENUM_FIELD(YVYU, 0x55595659),
    TD_YAML_ENUM_FIELD(NV12, 0x3231564e),
    TD_YAML_ENUM_FIELD(NV21, 0x3132564e),
    TD_YAML_ENUM_FIELD(P010, 0x30313050),
    TD_YAML_ENUM_FIELD(EXTERNAL_OES, 0x2053454f),
    TD_YAML_ENUM_FIELD(MJPG, 0x47504a4d)
)