#pragma once
#include "TwoD/Serialization/Serialization.hpp"

namespace TwoD
{
    class Window;
}

TD_ENUM(
	(TD_NAMESPACE(TwoD), TD_NAME(WindowFlags), TD_BASE(uint64_t)),
	(
		TD_ENUM_FIELD(FULLSCREEN, TD_INIT(0x0000000000000001ULL)),
		TD_ENUM_FIELD(OPENGL, TD_INIT(0x0000000000000002ULL)),
		TD_ENUM_FIELD(OCCLUDED, TD_INIT(0x0000000000000004ULL)),
		TD_ENUM_FIELD(HIDDEN, TD_INIT(0x0000000000000008ULL)),
		TD_ENUM_FIELD(BORDERLESS, TD_INIT(0x0000000000000010ULL)),
		TD_ENUM_FIELD(RESIZABLE, TD_INIT(0x0000000000000020ULL)),
		TD_ENUM_FIELD(MINIMIZED, TD_INIT(0x0000000000000040ULL)),
		TD_ENUM_FIELD(MAXIMIZED, TD_INIT(0x0000000000000080ULL)),
		TD_ENUM_FIELD(MOUSE_GRABBED, TD_INIT(0x0000000000000100ULL)),
		TD_ENUM_FIELD(INPUT_FOCUS, TD_INIT(0x0000000000000200ULL)),
		TD_ENUM_FIELD(MOUSE_FOCUS, TD_INIT(0x0000000000000400ULL)),
		TD_ENUM_FIELD(EXTERNAL, TD_INIT(0x0000000000000800ULL)),
		TD_ENUM_FIELD(MODAL, TD_INIT(0x0000000000001000ULL)),
		TD_ENUM_FIELD(HIGH_PIXEL_DENSITY, TD_INIT(0x0000000000002000ULL)),
		TD_ENUM_FIELD(MOUSE_CAPTURE, TD_INIT(0x0000000000004000ULL)),
		TD_ENUM_FIELD(MOUSE_RELATIVE_MODE, TD_INIT(0x0000000000008000ULL)),
		TD_ENUM_FIELD(ALWAYS_ON_TOP, TD_INIT(0x0000000000010000ULL)),
		TD_ENUM_FIELD(UTILITY, TD_INIT(0x0000000000020000ULL)),
		TD_ENUM_FIELD(TOOLTIP, TD_INIT(0x0000000000040000ULL)),
		TD_ENUM_FIELD(POPUP_MENU, TD_INIT(0x0000000000080000ULL)),
		TD_ENUM_FIELD(KEYBOARD_GRABBED, TD_INIT(0x0000000000100000ULL)),
		TD_ENUM_FIELD(VULKAN, TD_INIT(0x0000000010000000ULL)),
		TD_ENUM_FIELD(METAL, TD_INIT(0x0000000020000000ULL)),
		TD_ENUM_FIELD(W_TRANSPARENT, TD_INIT(0x0000000040000000ULL)),
		TD_ENUM_FIELD(NOT_FOCUSABLE, TD_INIT(0x0000000080000000ULL))
	)
)

TD_STRUCT(
	(TD_NAMESPACE(TwoD), TD_NAME(WindowInfo)),
	(
		TD_STRUCT_FIELD(int, width),
		TD_STRUCT_FIELD(int, height),
		TD_STRUCT_FIELD(std::string, title),
		TD_STRUCT_FIELD(TwoD::WindowFlags, windowFlags)
	),
)

namespace TwoD::SDL
{
    // *****************************************************
    // Declerations ****************************************
    // *****************************************************

    class Surface;
    class Texture;
    class Sampler;
    class Buffer;
    class CommandBuffer;
    class CopyPass;
    class GraphicsPipeline;
    class RenderPass;
    class Shader;
    class TransferBuffer;
	class Fence;

	class AudioSource;
	class AudioStream;
}
	
// *****************************************************
// Misc ************************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(Filter)),
	(
		TD_ENUM_FIELD(NEAREST),
		TD_ENUM_FIELD(LINEAR)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(CompareOp)),
	(
		TD_ENUM_FIELD(INVALID),
		TD_ENUM_FIELD(NEVER),
		TD_ENUM_FIELD(LESS),
		TD_ENUM_FIELD(EQUAL),
		TD_ENUM_FIELD(LESS_OR_EQUAL),
		TD_ENUM_FIELD(GREATER),
		TD_ENUM_FIELD(NOT_EQUAL),
		TD_ENUM_FIELD(GREATER_OR_EQUAL),
		TD_ENUM_FIELD(ALWAYS)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BlendFactor)),
	(
		TD_ENUM_FIELD(INVALID),
		TD_ENUM_FIELD(ZERO),
		TD_ENUM_FIELD(ONE),
		TD_ENUM_FIELD(SRC_COLOR),
		TD_ENUM_FIELD(ONE_MINUS_SRC_COLOR),
		TD_ENUM_FIELD(DST_COLOR),
		TD_ENUM_FIELD(ONE_MINUS_DST_COLOR),
		TD_ENUM_FIELD(SRC_ALPHA),
		TD_ENUM_FIELD(ONE_MINUS_SRC_ALPHA),
		TD_ENUM_FIELD(DST_ALPHA),
		TD_ENUM_FIELD(ONE_MINUS_DST_ALPHA),
		TD_ENUM_FIELD(CONSTANT_COLOR),
		TD_ENUM_FIELD(ONE_MINUS_CONSTANT_COLOR),
		TD_ENUM_FIELD(SRC_ALPHA_SATURATE)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BlendOp)),
	(
		TD_ENUM_FIELD(INVALID),
		TD_ENUM_FIELD(ADD),
		TD_ENUM_FIELD(SUBTRACT),
		TD_ENUM_FIELD(REVERSE_SUBTRACT),
		TD_ENUM_FIELD(MIN),
		TD_ENUM_FIELD(MAX)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(SampleCount)),
	(
		TD_ENUM_FIELD(ONE),
		TD_ENUM_FIELD(TWO),
		TD_ENUM_FIELD(FOUR),
		TD_ENUM_FIELD(EIGHT)
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(Rect)),
	(
		TD_STRUCT_FIELD(uint32_t, x, TD_INIT(0)),
		TD_STRUCT_FIELD(uint32_t, y, TD_INIT(0)),
		TD_STRUCT_FIELD(uint32_t, w, TD_INIT(0)),
		TD_STRUCT_FIELD(uint32_t, h, TD_INIT(0))
	),
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(LoadOp)),
	(
		TD_ENUM_FIELD(LOAD),
		TD_ENUM_FIELD(CLEAR),
		TD_ENUM_FIELD(DONT_CARE)
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(FColor)),
	(
		TD_STRUCT_FIELD(float, r, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(float, g, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(float, b, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(float, a, TD_INIT(0.0f))
	),
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(FlipMode)),
	(
		TD_ENUM_FIELD(NONE),
		TD_ENUM_FIELD(HORIZONTAL),
		TD_ENUM_FIELD(VERTICAL)
	)
)

// *****************************************************
// Buffer **********************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BufferUsage), TD_BASE(uint32_t)),
	(
		TD_ENUM_FIELD(VERTEX, TD_INIT(1u << 0)),
		TD_ENUM_FIELD(INDEX, TD_INIT(1u << 1)),
		TD_ENUM_FIELD(INDIRECT, TD_INIT(1u << 2)),
		TD_ENUM_FIELD(GRAPHICS_STORAGE_READ, TD_INIT(1u << 3)),
		TD_ENUM_FIELD(COMPUTE_STORAGE_READ, TD_INIT(1u << 4)),
		TD_ENUM_FIELD(COMPUTE_STORAGE_WRITE, TD_INIT(1u << 5))
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BufferInfo)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::BufferUsage, usage),
		TD_STRUCT_FIELD(uint32_t, size)
	),
)

// *****************************************************
// TransferBuffer **************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TransferBufferUsage)),
	(
		TD_ENUM_FIELD(UPLOAD),
		TD_ENUM_FIELD(DOWNLOAD)
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TransferBufferInfo)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::TransferBufferUsage, usage),
		TD_STRUCT_FIELD(uint32_t, size)
	),
)

// *****************************************************
// Texture *********************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TextureFormat)),
	(
		TD_ENUM_FIELD(INVALID),
		TD_ENUM_FIELD(A8_UNORM),
		TD_ENUM_FIELD(R8_UNORM),
		TD_ENUM_FIELD(R8G8_UNORM),
		TD_ENUM_FIELD(R8G8B8A8_UNORM),
		TD_ENUM_FIELD(R16_UNORM),
		TD_ENUM_FIELD(R16G16_UNORM),
		TD_ENUM_FIELD(R16G16B16A16_UNORM),
		TD_ENUM_FIELD(R10G10B10A2_UNORM),
		TD_ENUM_FIELD(B5G6R5_UNORM),
		TD_ENUM_FIELD(B5G5R5A1_UNORM),
		TD_ENUM_FIELD(B4G4R4A4_UNORM),
		TD_ENUM_FIELD(B8G8R8A8_UNORM),
		TD_ENUM_FIELD(BC1_RGBA_UNORM),
		TD_ENUM_FIELD(BC2_RGBA_UNORM),
		TD_ENUM_FIELD(BC3_RGBA_UNORM),
		TD_ENUM_FIELD(BC4_R_UNORM),
		TD_ENUM_FIELD(BC5_RG_UNORM),
		TD_ENUM_FIELD(BC7_RGBA_UNORM),
		TD_ENUM_FIELD(BC6H_RGB_FLOAT),
		TD_ENUM_FIELD(BC6H_RGB_UFLOAT),
		TD_ENUM_FIELD(R8_SNORM),
		TD_ENUM_FIELD(R8G8_SNORM),
		TD_ENUM_FIELD(R8G8B8A8_SNORM),
		TD_ENUM_FIELD(R16_SNORM),
		TD_ENUM_FIELD(R16G16_SNORM),
		TD_ENUM_FIELD(R16G16B16A16_SNORM),
		TD_ENUM_FIELD(R16_FLOAT),
		TD_ENUM_FIELD(R16G16_FLOAT),
		TD_ENUM_FIELD(R16G16B16A16_FLOAT),
		TD_ENUM_FIELD(R32_FLOAT),
		TD_ENUM_FIELD(R32G32_FLOAT),
		TD_ENUM_FIELD(R32G32B32A32_FLOAT),
		TD_ENUM_FIELD(R11G11B10_UFLOAT),
		TD_ENUM_FIELD(R8_UINT),
		TD_ENUM_FIELD(R8G8_UINT),
		TD_ENUM_FIELD(R8G8B8A8_UINT),
		TD_ENUM_FIELD(R16_UINT),
		TD_ENUM_FIELD(R16G16_UINT),
		TD_ENUM_FIELD(R16G16B16A16_UINT),
		TD_ENUM_FIELD(R32_UINT),
		TD_ENUM_FIELD(R32G32_UINT),
		TD_ENUM_FIELD(R32G32B32A32_UINT),
		TD_ENUM_FIELD(R8_INT),
		TD_ENUM_FIELD(R8G8_INT),
		TD_ENUM_FIELD(R8G8B8A8_INT),
		TD_ENUM_FIELD(R16_INT),
		TD_ENUM_FIELD(R16G16_INT),
		TD_ENUM_FIELD(R16G16B16A16_INT),
		TD_ENUM_FIELD(R32_INT),
		TD_ENUM_FIELD(R32G32_INT),
		TD_ENUM_FIELD(R32G32B32A32_INT),
		TD_ENUM_FIELD(R8G8B8A8_UNORM_SRGB),
		TD_ENUM_FIELD(B8G8R8A8_UNORM_SRGB),
		TD_ENUM_FIELD(BC1_RGBA_UNORM_SRGB),
		TD_ENUM_FIELD(BC2_RGBA_UNORM_SRGB),
		TD_ENUM_FIELD(BC3_RGBA_UNORM_SRGB),
		TD_ENUM_FIELD(BC7_RGBA_UNORM_SRGB),
		TD_ENUM_FIELD(D16_UNORM),
		TD_ENUM_FIELD(D24_UNORM),
		TD_ENUM_FIELD(D32_FLOAT),
		TD_ENUM_FIELD(D24_UNORM_S8_UINT),
		TD_ENUM_FIELD(D32_FLOAT_S8_UINT),
		TD_ENUM_FIELD(ASTC_4x4_UNORM),
		TD_ENUM_FIELD(ASTC_5x4_UNORM),
		TD_ENUM_FIELD(ASTC_5x5_UNORM),
		TD_ENUM_FIELD(ASTC_6x5_UNORM),
		TD_ENUM_FIELD(ASTC_6x6_UNORM),
		TD_ENUM_FIELD(ASTC_8x5_UNORM),
		TD_ENUM_FIELD(ASTC_8x6_UNORM),
		TD_ENUM_FIELD(ASTC_8x8_UNORM),
		TD_ENUM_FIELD(ASTC_10x5_UNORM),
		TD_ENUM_FIELD(ASTC_10x6_UNORM),
		TD_ENUM_FIELD(ASTC_10x8_UNORM),
		TD_ENUM_FIELD(ASTC_10x10_UNORM),
		TD_ENUM_FIELD(ASTC_12x10_UNORM),
		TD_ENUM_FIELD(ASTC_12x12_UNORM),
		TD_ENUM_FIELD(ASTC_4x4_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_5x4_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_5x5_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_6x5_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_6x6_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_8x5_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_8x6_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_8x8_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_10x5_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_10x6_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_10x8_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_10x10_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_12x10_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_12x12_UNORM_SRGB),
		TD_ENUM_FIELD(ASTC_4x4_FLOAT),
		TD_ENUM_FIELD(ASTC_5x4_FLOAT),
		TD_ENUM_FIELD(ASTC_5x5_FLOAT),
		TD_ENUM_FIELD(ASTC_6x5_FLOAT),
		TD_ENUM_FIELD(ASTC_6x6_FLOAT),
		TD_ENUM_FIELD(ASTC_8x5_FLOAT),
		TD_ENUM_FIELD(ASTC_8x6_FLOAT),
		TD_ENUM_FIELD(ASTC_8x8_FLOAT),
		TD_ENUM_FIELD(ASTC_10x5_FLOAT),
		TD_ENUM_FIELD(ASTC_10x6_FLOAT),
		TD_ENUM_FIELD(ASTC_10x8_FLOAT),
		TD_ENUM_FIELD(ASTC_10x10_FLOAT),
		TD_ENUM_FIELD(ASTC_12x10_FLOAT),
		TD_ENUM_FIELD(ASTC_12x12_FLOAT)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TextureType)),
	(
		TD_ENUM_FIELD(TWO_D),
		TD_ENUM_FIELD(TWO_D_ARRAY),
		TD_ENUM_FIELD(THREE_D),
		TD_ENUM_FIELD(CUBE),
		TD_ENUM_FIELD(CUBE_ARRAY)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TextureUsageFlags), TD_BASE(uint32_t)),
	(
		TD_ENUM_FIELD(SAMPLER, TD_INIT(1u << 0)),
		TD_ENUM_FIELD(COLOR_TARGET, TD_INIT(1u << 1)),
		TD_ENUM_FIELD(DEPTH_STENCIL_TARGET, TD_INIT(1u << 2)),
		TD_ENUM_FIELD(GRAPHICS_STORAGE_READ, TD_INIT(1u << 3)),
		TD_ENUM_FIELD(COMPUTE_STORAGE_READ, TD_INIT(1u << 4)),
		TD_ENUM_FIELD(COMPUTE_STORAGE_WRITE, TD_INIT(1u << 5)),
		TD_ENUM_FIELD(COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE, TD_INIT(1u << 6))
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TextureInfo)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::TextureType, type),
		TD_STRUCT_FIELD(TwoD::SDL::TextureFormat, format),
		TD_STRUCT_FIELD(TwoD::SDL::TextureUsageFlags, usage),
		TD_STRUCT_FIELD(uint32_t, width),
		TD_STRUCT_FIELD(uint32_t, height),
		TD_STRUCT_FIELD(uint32_t, layerCountOrDepth, TD_INIT(1)),
		TD_STRUCT_FIELD(uint32_t, numLevels, TD_INIT(1)),
		TD_STRUCT_FIELD(TwoD::SDL::SampleCount, sampleCount, TD_INIT(TwoD::SDL::SampleCount::ONE))
	),
)

TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BlitRegion)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::Texture*, texture, TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(uint32_t, mipLevel, TD_INIT(1)),
		TD_STRUCT_FIELD(uint32_t, layerOrDepthPlane, TD_INIT(1)),
		TD_STRUCT_FIELD(uint32_t, x, TD_INIT(0)),
		TD_STRUCT_FIELD(uint32_t, y, TD_INIT(0)),
		TD_STRUCT_FIELD(uint32_t, w, TD_INIT(0)),
		TD_STRUCT_FIELD(uint32_t, h, TD_INIT(0))
	),
)

TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BlitInfo)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::BlitRegion, source, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::BlitRegion, destination, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::LoadOp, loadOp, TD_INIT(TwoD::SDL::LoadOp::DONT_CARE)),
		TD_STRUCT_FIELD(TwoD::SDL::FColor, clearColor, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::FlipMode, flipMode, TD_INIT(TwoD::SDL::FlipMode::NONE)),
		TD_STRUCT_FIELD(TwoD::SDL::Filter, filter, TD_INIT(TwoD::SDL::Filter::LINEAR)),
		TD_STRUCT_FIELD(bool, cycle, TD_INIT(false))
	),
)

// *****************************************************
// Sampler *********************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(SamplerMipmapMode)),
	(
		TD_ENUM_FIELD(NEAREST),
		TD_ENUM_FIELD(LINEAR)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(SamplerAddressMode)),
	(
		TD_ENUM_FIELD(REPEAT),
		TD_ENUM_FIELD(MIRRORED_REPEAT),
		TD_ENUM_FIELD(CLAMP_TO_EDGE)
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(SamplerInfo)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::Filter, minFilter),
		TD_STRUCT_FIELD(TwoD::SDL::Filter, magFilter),
		TD_STRUCT_FIELD(TwoD::SDL::SamplerMipmapMode, mipmapMode),
		TD_STRUCT_FIELD(TwoD::SDL::SamplerAddressMode, addressModeU),
		TD_STRUCT_FIELD(TwoD::SDL::SamplerAddressMode, addressModeV),
		TD_STRUCT_FIELD(TwoD::SDL::SamplerAddressMode, addressModeW),
		TD_STRUCT_FIELD(float, mipLodBias, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(float, maxAnisotropy, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(TwoD::SDL::CompareOp, compareOp, TD_INIT(TwoD::SDL::CompareOp::INVALID)),
		TD_STRUCT_FIELD(float, minLod, TD_INIT(0)),
		TD_STRUCT_FIELD(float, maxLod, TD_INIT(0)),
		TD_STRUCT_FIELD(bool, enableAnisotropy, TD_INIT(false)),
		TD_STRUCT_FIELD(bool, enableCompare, TD_INIT(false))
	),
)

// *****************************************************
// Shader **********************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(ShaderFormat), TD_BASE(uint32_t)),
	(
		TD_ENUM_FIELD(INVALID,  TD_INIT(0)),
		TD_ENUM_FIELD(PRIVATE,  TD_INIT(1u << 0)),
		TD_ENUM_FIELD(SPIRV,    TD_INIT(1u << 1)),
		TD_ENUM_FIELD(DXBC,     TD_INIT(1u << 2)),
		TD_ENUM_FIELD(DXIL,     TD_INIT(1u << 3)),
		TD_ENUM_FIELD(MSL,      TD_INIT(1u << 4)),
		TD_ENUM_FIELD(METALLIB, TD_INIT(1u << 5))
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(ShaderStage)),
	(
		TD_ENUM_FIELD(VERTEX),
		TD_ENUM_FIELD(FRAGMENT)
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(ShaderInfo)),
	(
		TD_STRUCT_FIELD(uint32_t, codeSize),
		TD_STRUCT_FIELD(uint8_t*, code, TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(std::string, entrypoint),
		TD_STRUCT_FIELD(TwoD::SDL::ShaderFormat, format),
		TD_STRUCT_FIELD(TwoD::SDL::ShaderStage, stage),
		TD_STRUCT_FIELD(uint32_t, numSamplers),
		TD_STRUCT_FIELD(uint32_t, numStorageTextures),
		TD_STRUCT_FIELD(uint32_t, numStorageBuffers),
		TD_STRUCT_FIELD(uint32_t, numUniformBuffers)
	),
)

// *****************************************************
// RenderPass ******************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(IndexElementSize)),
	(
		TD_ENUM_FIELD(SIXTEEN_BIT),
		TD_ENUM_FIELD(THIRTY_TWO_BIT)
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TextureSamplerBinding)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::Texture*, texture, TD_INIT(nullptr), TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(TwoD::SDL::Sampler*, sampler, TD_INIT(nullptr), TD_NO_SERIALIZE, TD_NO_DEBUG)
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BufferBinding)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::Buffer*, buffer, TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(uint32_t, offset)
	),
)

// *****************************************************
// CopyPass ********************************************
// *****************************************************

TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TextureTransferInfo)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::TransferBuffer*, transferBuffer, TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(uint32_t, offset),
		TD_STRUCT_FIELD(uint32_t, pixelsPerRow),
		TD_STRUCT_FIELD(uint32_t, rowsPerLayer)
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TextureRegion)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::Texture*, texture, TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(uint32_t, mipLevel),
		TD_STRUCT_FIELD(uint32_t, layer),
		TD_STRUCT_FIELD(uint32_t, x),
		TD_STRUCT_FIELD(uint32_t, y),
		TD_STRUCT_FIELD(uint32_t, z),
		TD_STRUCT_FIELD(uint32_t, w),
		TD_STRUCT_FIELD(uint32_t, h),
		TD_STRUCT_FIELD(uint32_t, d)
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(TransferBufferLocation)),
	(
		TD_STRUCT_FIELD(const TwoD::SDL::TransferBuffer*, transferBuffer, TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(uint32_t, offset)
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(BufferRegion)),
	(
		TD_STRUCT_FIELD(const TwoD::SDL::Buffer*, buffer, TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(uint32_t, offset),
		TD_STRUCT_FIELD(uint32_t, size)
	),
)

// *****************************************************
// GraphicsPipeline ************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(VertexElementFormat)),
	(
		TD_ENUM_FIELD(INVALID),
		TD_ENUM_FIELD(INT),
		TD_ENUM_FIELD(INT2),
		TD_ENUM_FIELD(INT3),
		TD_ENUM_FIELD(INT4),
		TD_ENUM_FIELD(UINT),
		TD_ENUM_FIELD(UINT2),
		TD_ENUM_FIELD(UINT3),
		TD_ENUM_FIELD(UINT4),
		TD_ENUM_FIELD(FLOAT),
		TD_ENUM_FIELD(FLOAT2),
		TD_ENUM_FIELD(FLOAT3),
		TD_ENUM_FIELD(FLOAT4),
		TD_ENUM_FIELD(BYTE2),
		TD_ENUM_FIELD(BYTE4),
		TD_ENUM_FIELD(UBYTE2),
		TD_ENUM_FIELD(UBYTE4),
		TD_ENUM_FIELD(BYTE2_NORM),
		TD_ENUM_FIELD(BYTE4_NORM)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(VertexInputRate)),
	(
		TD_ENUM_FIELD(VERTEX),
		TD_ENUM_FIELD(INSTANCE)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(PrimitiveType)),
	(
		TD_ENUM_FIELD(TRIANGLELIST),
		TD_ENUM_FIELD(TRIANGLESTRIP),
		TD_ENUM_FIELD(LINELIST),
		TD_ENUM_FIELD(LINESTRIP),
		TD_ENUM_FIELD(POINTLIST)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(FrontFace)),
	(
		TD_ENUM_FIELD(COUNTER_CLOCKWISE),
		TD_ENUM_FIELD(CLOCKWISE)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(CullMode)),
	(
		TD_ENUM_FIELD(NONE),
		TD_ENUM_FIELD(FRONT),
		TD_ENUM_FIELD(BACK)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(FillMode)),
	(
		TD_ENUM_FIELD(FILL),
		TD_ENUM_FIELD(LINE)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(StencilOp)),
	(
		TD_ENUM_FIELD(INVALID),
		TD_ENUM_FIELD(KEEP),
		TD_ENUM_FIELD(ZERO),
		TD_ENUM_FIELD(REPLACE),
		TD_ENUM_FIELD(INCREMENT_AND_CLAMP),
		TD_ENUM_FIELD(DECREMENT_AND_CLAMP),
		TD_ENUM_FIELD(INVERT),
		TD_ENUM_FIELD(INCREMENT_AND_WRAP),
		TD_ENUM_FIELD(DECREMENT_AND_WRAP)
	)
)
TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(ColorComponentFlags), TD_BASE(uint8_t)),
	(
		TD_ENUM_FIELD(R, TD_INIT(1u << 0)),
		TD_ENUM_FIELD(G, TD_INIT(1u << 1)),
		TD_ENUM_FIELD(B, TD_INIT(1u << 2)),
		TD_ENUM_FIELD(A, TD_INIT(1u << 3))
	)
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(ColorTargetBlendState)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::BlendFactor, srcColorBlendfactor, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::BlendFactor, dstColorBlendfactor, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::BlendOp, colorBlendOp, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::BlendFactor, srcAlphaBlendfactor, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::BlendFactor, dstAlphaBlendfactor, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::BlendOp, alphaBlendOp, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::ColorComponentFlags, colorWriteMask, TD_INIT({})),
		TD_STRUCT_FIELD(bool, enableBlend, TD_INIT(false)),
		TD_STRUCT_FIELD(bool, enableColorWriteMask, TD_INIT(false))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(VertexBufferDescription)),
	(
		TD_STRUCT_FIELD(uint32_t, slot),
		TD_STRUCT_FIELD(uint32_t, pitch),
		TD_STRUCT_FIELD(TwoD::SDL::VertexInputRate, inputRate)
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(VertexAttribute)),
	(
		TD_STRUCT_FIELD(uint32_t, location),
		TD_STRUCT_FIELD(uint32_t, bufferSlot),
		TD_STRUCT_FIELD(TwoD::SDL::VertexElementFormat, format),
		TD_STRUCT_FIELD(uint32_t, offset)
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(StencilOpState)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::StencilOp, failOp, TD_INIT(TwoD::SDL::StencilOp::INVALID)),
		TD_STRUCT_FIELD(TwoD::SDL::StencilOp, passOp, TD_INIT(TwoD::SDL::StencilOp::INVALID)),
		TD_STRUCT_FIELD(TwoD::SDL::StencilOp, depthFailOp, TD_INIT(TwoD::SDL::StencilOp::INVALID)),
		TD_STRUCT_FIELD(TwoD::SDL::CompareOp, compareOp, TD_INIT(TwoD::SDL::CompareOp::INVALID))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(ColorTargetDescription)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::TextureFormat, format, TD_INIT(TwoD::SDL::TextureFormat::INVALID)),
		TD_STRUCT_FIELD(TwoD::SDL::ColorTargetBlendState, blendState, TD_INIT({}))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(VertexInputState)),
	(
		TD_STRUCT_FIELD(std::vector<TwoD::SDL::VertexBufferDescription>, vertexBufferDescriptions, TD_INIT({})),
		TD_STRUCT_FIELD(std::vector<TwoD::SDL::VertexAttribute>, vertexAttributes, TD_INIT({}))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(RasterizerState)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::FillMode, fillMode, TD_INIT(TwoD::SDL::FillMode::FILL)),
		TD_STRUCT_FIELD(TwoD::SDL::CullMode, cullMode, TD_INIT(TwoD::SDL::CullMode::NONE)),
		TD_STRUCT_FIELD(TwoD::SDL::FrontFace, frontFace, TD_INIT(TwoD::SDL::FrontFace::COUNTER_CLOCKWISE)),
		TD_STRUCT_FIELD(float, depthBiasConstantFactor, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(float, depthBiasClamp, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(float, depthBiasSlopeFactor, TD_INIT(0.0f)),
		TD_STRUCT_FIELD(bool, enableDepthBias, TD_INIT(false)),
		TD_STRUCT_FIELD(bool, enableDepthClip, TD_INIT(false))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(MultisampleState)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::SampleCount, sampleCount, TD_INIT(TwoD::SDL::SampleCount::ONE)),
		TD_STRUCT_FIELD(uint32_t, sampleMask, TD_INIT(0)),
		TD_STRUCT_FIELD(bool, enableMask, TD_INIT(false))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(DepthStencilState)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::CompareOp, compareOp, TD_INIT(TwoD::SDL::CompareOp::INVALID)),
		TD_STRUCT_FIELD(TwoD::SDL::StencilOpState, backStencilState, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::StencilOpState, frontStencilState, TD_INIT({})),
		TD_STRUCT_FIELD(uint8_t, compareMask, TD_INIT(0)),
		TD_STRUCT_FIELD(uint8_t, writeMask, TD_INIT(0)),
		TD_STRUCT_FIELD(bool, enableDepthTest, TD_INIT(false)),
		TD_STRUCT_FIELD(bool, enableDepthWrite, TD_INIT(false)),
		TD_STRUCT_FIELD(bool, enableStencilTest, TD_INIT(false))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(GraphicsPipelineTargetInfo)),
	(
		TD_STRUCT_FIELD(std::vector<TwoD::SDL::ColorTargetDescription>, colorTargetDescriptions, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::TextureFormat, depthStencilFormat, TD_INIT(TwoD::SDL::TextureFormat::INVALID)),
		TD_STRUCT_FIELD(bool, hasDepthStencilTarget, TD_INIT(false))
	),
)
TD_STRUCT(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(GraphicsPipelineInfo)),
	(
		TD_STRUCT_FIELD(TwoD::SDL::Shader*, vertexShader, TD_INIT(nullptr), TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(TwoD::SDL::Shader*, fragmentShader, TD_INIT(nullptr), TD_NO_SERIALIZE, TD_NO_DEBUG),
		TD_STRUCT_FIELD(TwoD::SDL::VertexInputState, vertexInputState, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::PrimitiveType, primitiveType, TD_INIT(TwoD::SDL::PrimitiveType::TRIANGLELIST)),
		TD_STRUCT_FIELD(TwoD::SDL::RasterizerState, rasterizerState, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::MultisampleState, multisampleState, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::DepthStencilState, depthStencilState, TD_INIT({})),
		TD_STRUCT_FIELD(TwoD::SDL::GraphicsPipelineTargetInfo, targetInfo, TD_INIT({}))
	),
)

// *****************************************************
// Surface *********************************************
// *****************************************************

TD_ENUM(
	(TD_NAMESPACE(TwoD::SDL), TD_NAME(PixelFormat)),
	(
		TD_ENUM_FIELD(UNKNOWN, TD_INIT(0)),
		TD_ENUM_FIELD(INDEX1LSB, TD_INIT(0x11100100u)),
		TD_ENUM_FIELD(INDEX1MSB, TD_INIT(0x11200100u)),
		TD_ENUM_FIELD(INDEX2LSB, TD_INIT(0x1c100200u)),
		TD_ENUM_FIELD(INDEX2MSB, TD_INIT(0x1c200200u)),
		TD_ENUM_FIELD(INDEX4LSB, TD_INIT(0x12100400u)),
		TD_ENUM_FIELD(INDEX4MSB, TD_INIT(0x12200400u)),
		TD_ENUM_FIELD(INDEX8, TD_INIT(0x13000801u)),
		TD_ENUM_FIELD(RGB332, TD_INIT(0x14110801u)),
		TD_ENUM_FIELD(XRGB4444, TD_INIT(0x15120c02u)),
		TD_ENUM_FIELD(XBGR4444, TD_INIT(0x15520c02u)),
		TD_ENUM_FIELD(XRGB1555, TD_INIT(0x15130f02u)),
		TD_ENUM_FIELD(XBGR1555, TD_INIT(0x15530f02u)),
		TD_ENUM_FIELD(ARGB4444, TD_INIT(0x15321002u)),
		TD_ENUM_FIELD(RGBA4444, TD_INIT(0x15421002u)),
		TD_ENUM_FIELD(ABGR4444, TD_INIT(0x15721002u)),
		TD_ENUM_FIELD(BGRA4444, TD_INIT(0x15821002u)),
		TD_ENUM_FIELD(ARGB1555, TD_INIT(0x15331002u)),
		TD_ENUM_FIELD(RGBA5551, TD_INIT(0x15441002u)),
		TD_ENUM_FIELD(ABGR1555, TD_INIT(0x15731002u)),
		TD_ENUM_FIELD(BGRA5551, TD_INIT(0x15841002u)),
		TD_ENUM_FIELD(RGB565, TD_INIT(0x15151002u)),
		TD_ENUM_FIELD(BGR565, TD_INIT(0x15551002u)),
		TD_ENUM_FIELD(RGB24, TD_INIT(0x17101803u)),
		TD_ENUM_FIELD(BGR24, TD_INIT(0x17401803u)),
		TD_ENUM_FIELD(XRGB8888, TD_INIT(0x16161804u)),
		TD_ENUM_FIELD(RGBX8888, TD_INIT(0x16261804u)),
		TD_ENUM_FIELD(XBGR8888, TD_INIT(0x16561804u)),
		TD_ENUM_FIELD(BGRX8888, TD_INIT(0x16661804u)),
		TD_ENUM_FIELD(ARGB8888, TD_INIT(0x16362004u)),
		TD_ENUM_FIELD(RGBA8888, TD_INIT(0x16462004u)),
		TD_ENUM_FIELD(ABGR8888, TD_INIT(0x16762004u)),
		TD_ENUM_FIELD(BGRA8888, TD_INIT(0x16862004u)),
		TD_ENUM_FIELD(XRGB2101010, TD_INIT(0x16172004u)),
		TD_ENUM_FIELD(XBGR2101010, TD_INIT(0x16572004u)),
		TD_ENUM_FIELD(ARGB2101010, TD_INIT(0x16372004u)),
		TD_ENUM_FIELD(ABGR2101010, TD_INIT(0x16772004u)),
		TD_ENUM_FIELD(RGB48, TD_INIT(0x18103006u)),
		TD_ENUM_FIELD(BGR48, TD_INIT(0x18403006u)),
		TD_ENUM_FIELD(RGBA64, TD_INIT(0x18204008u)),
		TD_ENUM_FIELD(ARGB64, TD_INIT(0x18304008u)),
		TD_ENUM_FIELD(BGRA64, TD_INIT(0x18504008u)),
		TD_ENUM_FIELD(ABGR64, TD_INIT(0x18604008u)),
		TD_ENUM_FIELD(RGB48_FLOAT, TD_INIT(0x1a103006u)),
		TD_ENUM_FIELD(BGR48_FLOAT, TD_INIT(0x1a403006u)),
		TD_ENUM_FIELD(RGBA64_FLOAT, TD_INIT(0x1a204008u)),
		TD_ENUM_FIELD(ARGB64_FLOAT, TD_INIT(0x1a304008u)),
		TD_ENUM_FIELD(BGRA64_FLOAT, TD_INIT(0x1a504008u)),
		TD_ENUM_FIELD(ABGR64_FLOAT, TD_INIT(0x1a604008u)),
		TD_ENUM_FIELD(RGB96_FLOAT, TD_INIT(0x1b10600cu)),
		TD_ENUM_FIELD(BGR96_FLOAT, TD_INIT(0x1b40600cu)),
		TD_ENUM_FIELD(RGBA128_FLOAT, TD_INIT(0x1b208010u)),
		TD_ENUM_FIELD(ARGB128_FLOAT, TD_INIT(0x1b308010u)),
		TD_ENUM_FIELD(BGRA128_FLOAT, TD_INIT(0x1b508010u)),
		TD_ENUM_FIELD(ABGR128_FLOAT, TD_INIT(0x1b608010u)),
		TD_ENUM_FIELD(YV12, TD_INIT(0x32315659)),
		TD_ENUM_FIELD(IYUV, TD_INIT(0x56555949)),
		TD_ENUM_FIELD(YUY2, TD_INIT(0x32595559)),
		TD_ENUM_FIELD(UYVY, TD_INIT(0x59565955)),
		TD_ENUM_FIELD(YVYU, TD_INIT(0x55595659)),
		TD_ENUM_FIELD(NV12, TD_INIT(0x3231564e)),
		TD_ENUM_FIELD(NV21, TD_INIT(0x3132564e)),
		TD_ENUM_FIELD(P010, TD_INIT(0x30313050)),
		TD_ENUM_FIELD(EXTERNAL_OES, TD_INIT(0x2053454f)),
		TD_ENUM_FIELD(MJPG, TD_INIT(0x47504a4d))
	)
)